# Generated by Django 4.0.4 on 2022-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0002_alter_razvozka_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razvozka',
            name='to_do',
        ),
        migrations.AddField(
            model_name='razvozka',
            name='to_do_deliver',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='to_do_take',
            field=models.CharField(default='', max_length=255),
        ),
    ]
