# Generated by Django 4.0.4 on 2022-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0009_alter_razvozka_import_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_import',
            name='clr',
            field=models.CharField(default='text-secondary', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer_clr',
            name='clr',
            field=models.CharField(default='text-secondary', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_import',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka_import',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
