# Generated by Django 4.0.4 on 2022-05-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0010_customer_import_clr_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razvozka_import',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='razvozki.customer_clr'),
        ),
        migrations.DeleteModel(
            name='Customer_import',
        ),
    ]
