# Generated by Django 4.0.4 on 2022-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0011_alter_razvozka_import_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razvozka',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
