# Generated by Django 4.0.4 on 2022-05-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0012_alter_razvozka_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='razvozka',
            name='clr',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='razvozka_import',
            name='clr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
