# Generated by Django 4.0.4 on 2022-06-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0013_razvozka_clr_razvozka_import_clr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates_rzv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
            ],
        ),
    ]
