# Generated by Django 4.0.4 on 2022-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0014_dates_rzv'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates_rzv',
            name='date_begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dates_rzv',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
