# Generated by Django 4.0.4 on 2022-08-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0015_dates_rzv_date_begin_dates_rzv_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razvozka_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='True if active False if moved to Razvozki')),
                ('date_create', models.DateField(blank=True, help_text='date when created', null=True)),
                ('date_until', models.DateField(blank=True, help_text='latest date for transportation', null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('to_do_deliver', models.CharField(default='', max_length=255)),
                ('to_do_take', models.CharField(default='', max_length=255)),
                ('map_point', models.CharField(max_length=255)),
                ('deliver_to', models.BooleanField(default=False, help_text='transportation to processing')),
                ('return_from', models.BooleanField(default=False, help_text='return products from processing')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='razvozki.customer_clr')),
                ('return_goods', models.ForeignKey(blank=True, help_text='from which delivery return', null=True, on_delete=django.db.models.deletion.SET_NULL, to='razvozki.razvozka_plan')),
            ],
        ),
        migrations.DeleteModel(
            name='Dates_rzv',
        ),
        migrations.AddField(
            model_name='customer',
            name='subcontractor',
            field=models.BooleanField(default=False, help_text='True if subcontractor'),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='deliver_to',
            field=models.BooleanField(default=False, help_text='transportation to processing'),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='fulfilled',
            field=models.BooleanField(default=False, help_text='True is fulfilled'),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='return_all',
            field=models.BooleanField(default=False, help_text='False if some part was not return'),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='return_from',
            field=models.BooleanField(default=False, help_text='return products from processing'),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='return_goods',
            field=models.ForeignKey(blank=True, help_text='from which delivery return', null=True, on_delete=django.db.models.deletion.SET_NULL, to='razvozki.razvozka'),
        ),
        migrations.AddField(
            model_name='razvozka_import',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mappoint',
            field=models.CharField(default='', help_text='Yandex mappoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='address',
            field=models.CharField(help_text='real address', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='clr',
            field=models.CharField(default='', help_text='text color', max_length=30),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='contact',
            field=models.CharField(help_text='real contacts', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='customer base if exist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='razvozki.customer'),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='customer_name',
            field=models.CharField(help_text='customer as text could differ from db', max_length=100),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='date',
            field=models.DateField(help_text='date of transportation'),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='date_id',
            field=models.SmallIntegerField(default=0, help_text='order inside date'),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='map_point',
            field=models.CharField(help_text='Yandex mappoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='to_do_deliver',
            field=models.CharField(help_text='things for delivery', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka',
            name='to_do_take',
            field=models.CharField(help_text='things to take from', max_length=255),
        ),
        migrations.AlterField(
            model_name='razvozka_import',
            name='date_id',
            field=models.SmallIntegerField(default=1),
        ),
    ]
