# Generated by Django 4.0.4 on 2022-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0016_razvozka_plan_delete_dates_rzv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razvozka',
            name='fulfilled',
            field=models.BooleanField(default=True, help_text='True is fulfilled'),
        ),
    ]
