# Generated by Django 4.0.4 on 2022-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razvozki', '0017_alter_razvozka_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='razvozka',
            name='date_create',
            field=models.DateField(blank=True, default='2022-08-01', help_text='date of create razvozka', null=True),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='date_until',
            field=models.DateField(blank=True, default='2022-08-01', help_text='plan (last) date of transportation', null=True),
        ),
        migrations.DeleteModel(
            name='Razvozka_plan',
        ),
    ]
